# Generated by Django 5.0.3 on 2024-03-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='membership_date',
            field=models.DateField(blank=True, help_text='The date of the current type and status of membership, if applicable', null=True, verbose_name='Date of current membership type/status'),
        ),
    ]
