# Generated by Django 5.0.3 on 2024-03-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0002_alter_person_membership_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name_friendly_and_first',
        ),
        migrations.AddField(
            model_name='person',
            name='name_middles',
            field=models.CharField(default='', help_text="The person's middle names", max_length=100, verbose_name='middle names'),
            preserve_default=False,
        ),
    ]
