# Generated by Django 5.0.3 on 2024-03-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0003_remove_person_name_friendly_and_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='membership_date',
            field=models.DateField(blank=True, help_text='The date of the current class and status of membership, if applicable', null=True, verbose_name='membership status date'),
        ),
    ]
