# Generated by Django 5.0.3 on 2024-03-31 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0004_alter_person_membership_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The type of the image,', max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Name of the image',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefile', models.ImageField(upload_to='personimages', verbose_name='file')),
                ('person', models.ForeignKey(help_text='The person to which this link belongs', on_delete=django.db.models.deletion.CASCADE, to='sdc_people.person')),
                ('type', models.ForeignKey(blank=True, help_text='The type of image,', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_people.imagetype')),
            ],
        ),
    ]
