# Generated by Django 5.0.3 on 2024-03-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_people", "0005_imagetype_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Linkexternalname",
            new_name="Linkexternaltype",
        ),
        migrations.RenameField(
            model_name="linkexternal",
            old_name="name",
            new_name="type",
        ),
    ]
