# Generated by Django 5.0.3 on 2024-04-01 11:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0006_rename_linkexternalname_linkexternaltype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnotetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the type', max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Type of note',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='imagetype',
            options={'ordering': ('name',), 'verbose_name': 'Image type'},
        ),
        migrations.AlterModelOptions(
            name='meetingtype',
            options={'ordering': ('ordinal', 'name')},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='type',
            new_name='imagetype',
        ),
        migrations.RenameField(
            model_name='linkexternal',
            old_name='type',
            new_name='linkexternaltype',
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='ordinal',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Before Medium'), (5, 'Medium'), (6, 'After Medium'), (7, 'Third Last'), (8, 'Second Last'), (9, 'Last')], default=5, help_text='A number assigned for sorting, with lowest number first', verbose_name='ordinal'),
        ),
        migrations.AlterField(
            model_name='imagetype',
            name='name',
            field=models.CharField(help_text='The name of the type', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='linkexternaltype',
            name='name',
            field=models.CharField(help_text='The name of the type,', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='name',
            field=models.CharField(help_text='The name of the type', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='membershipclass',
            name='name',
            field=models.CharField(help_text='The name of the membership class,', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subcommitteetype',
            name='name',
            field=models.CharField(help_text='The name of the type,', max_length=50, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='Personnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, help_text='The content of the note', max_length=255)),
                ('when', models.DateTimeField(default=django.utils.timezone.now, help_text='The date of the note', verbose_name='date')),
                ('is_flagged', models.BooleanField(default=True, help_text='Flagged notes display an icon in the list view and appear by default in the detail view', verbose_name='is flagged')),
                ('author', models.ForeignKey(blank=True, help_text='The author of the note', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(help_text='The person to which this link belongs', on_delete=django.db.models.deletion.CASCADE, to='sdc_people.person')),
                ('personnotetype', models.ForeignKey(blank=True, help_text='The name of the link,', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_people.personnotetype')),
            ],
        ),
    ]
