# Generated by Django 5.0.3 on 2024-04-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0007_personnotetype_alter_imagetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('membershipclass', 'name_last', 'name_friendly'), 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='person',
            name='membershipclass',
            field=models.ForeignKey(help_text="The person's class of membership", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_people.membershipclass', verbose_name='membership class'),
        ),
    ]
