# Generated by Django 5.0.3 on 2024-04-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0008_alter_person_options_alter_person_membershipclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnote',
            name='expiration',
            field=models.BooleanField(blank=True, help_text='The expected or actual date when the note is no longer true', null=True, verbose_name='expiration date'),
        ),
    ]
