# Generated by Django 5.0.3 on 2024-04-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0009_personnote_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnote',
            name='expiration',
            field=models.DateField(blank=True, help_text='The expected or actual date when the note is no longer true', null=True, verbose_name='expiration date'),
        ),
    ]
