# Generated by Django 5.0.3 on 2024-04-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0011_subposition_display_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipclass',
            options={'ordering': ('ordinal', 'is_member', 'is_quorum_member', 'name'), 'verbose_name': 'membership class'},
        ),
    ]
