# Generated by Django 5.0.3 on 2024-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0012_alter_membershipclass_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipclass',
            name='is_member',
            field=models.IntegerField(choices=[(0, 'no'), (12, 'prospective'), (12, 'pending'), (111, 'yes')], default=0, help_text='If a person of this class is considered a member of the committee', verbose_name='is member'),
        ),
        migrations.AlterField(
            model_name='membershipclass',
            name='is_quorum_member',
            field=models.IntegerField(choices=[(0, 'no'), (12, 'pending'), (111, 'yes')], default=0, help_text='If a person of this class can be part of a quorum', verbose_name='is quorum member'),
        ),
    ]
