# Generated by Django 5.0.6 on 2024-09-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0013_alter_membershipclass_is_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('meeting', 'person__name_last')},
        ),
    ]
