# Generated by Django 5.0.6 on 2024-09-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0014_alter_attendance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('person__name_last', 'meeting')},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('name_last', 'name_friendly', 'membershipclass'), 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
