# Generated by Django 5.1.6 on 2025-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0015_alter_attendance_options_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='demog_is_veteran',
            field=models.BooleanField(default=False, help_text='Is this person a military veteran', verbose_name='veteran'),
        ),
    ]
