# Generated by Django 5.1.6 on 2025-03-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0016_person_demog_is_veteran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subposition',
            name='display_format',
            field=models.CharField(default='{position} {committee}', help_text='The format to display the subposition name and commmittee name in a list. Should include "{position}", "{committee}", or both', max_length=60),
        ),
    ]
