# Generated by Django 5.1.6 on 2025-03-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0017_alter_subposition_display_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subposition',
            name='display_format',
            field=models.CharField(default='{position} {committee}', max_length=60),
        ),
    ]
