# Generated by Django 5.1.6 on 2025-06-11 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0018_alter_subposition_display_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, help_text='The date this payment is/was due', null=True, verbose_name='due date')),
            ],
        ),
        migrations.CreateModel(
            name='Duestat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(blank=True, help_text='The effective date of the payment or waiver (the date the action counts as - which may be different from the actual date of transaction)', null=True, verbose_name='effective date')),
                ('status', models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Complete')], default=0, help_text='The status of this status assignment', verbose_name='status')),
                ('due', models.ForeignKey(help_text='The due which applies to this person', on_delete=django.db.models.deletion.CASCADE, to='sdc_people.due')),
                ('person', models.ForeignKey(help_text='The person to whom this dues action applies', on_delete=django.db.models.deletion.CASCADE, to='sdc_people.person')),
            ],
        ),
    ]
