# Generated by Django 5.2.7 on 2025-10-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0019_due_duestat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duestat',
            name='due',
        ),
        migrations.RemoveField(
            model_name='duestat',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dues_effective_date',
        ),
        migrations.AddField(
            model_name='person',
            name='dues_next',
            field=models.DateField(blank=True, help_text='The next dues payment date for this individual', null=True, verbose_name='Next Dues Date'),
        ),
        migrations.DeleteModel(
            name='Due',
        ),
        migrations.DeleteModel(
            name='Duestat',
        ),
    ]
