# Generated by Django 5.1.5 on 2025-04-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0019_due_duepersonstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DuePersonStatus',
            new_name='Duestat',
        ),
        migrations.RenameField(
            model_name='duestat',
            old_name='Due',
            new_name='due',
        ),
    ]
