# Generated by Django 5.2.7 on 2026-01-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0001_squashed_0020_remove_duestat_due_remove_duestat_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name_middles',
            field=models.CharField(help_text="The person's middle names", max_length=100, verbose_name='middle names'),
        ),
    ]
