# Generated by Django 5.2.7 on 2026-02-10 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_people', '0021_alter_person_name_middles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submembership',
            name='subposition',
        ),
        migrations.AlterModelOptions(
            name='submembership',
            options={'ordering': ('ordinal', 'person'), 'verbose_name': 'Subcommittee Membership'},
        ),
        migrations.AddField(
            model_name='submembership',
            name='ordinal',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Before Medium'), (5, 'Medium'), (6, 'After Medium'), (7, 'Third Last'), (8, 'Second Last'), (9, 'Last')], default=5, help_text='A number assigned for sorting, with lowest number first', verbose_name='ordinal'),
        ),
        migrations.AddField(
            model_name='submembership',
            name='position',
            field=models.CharField(default='Member', help_text='The name of the position', max_length=50, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='submembership',
            name='subcommittee',
            field=models.ForeignKey(help_text='The committee in which the person is a member', null=True, on_delete=django.db.models.deletion.CASCADE, to='sdc_people.subcommittee'),
        ),
        migrations.DeleteModel(
            name='Subposition',
        ),
    ]
